describe('1st Scenario', () => {
  it('1st Scenario', function() {
    cy.visit('https://demoqa.com');
    cy.get('.category-cards > :nth-child(2)').click();
    cy.get(':nth-child(2) > .element-list > .menu-list > #item-0').click();
    cy.waitUntil(() =>cy.get('h5').should('exist'));
    cy.get('#firstName').clear();
    cy.get('#firstName').type('Test');
    cy.get('#lastName').clear();
    cy.get('#lastName').type('Test');
    cy.get('#userEmail').clear();
    cy.get('#userEmail').type('test@test.com');
    cy.get('#genterWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').click();
    cy.get('#gender-radio-1').check();
    cy.get('#userNumber').clear('9');
    cy.get('#userNumber').type('9159159159');
    cy.get('#dateOfBirthInput').click();
    cy.get('#dateOfBirthInput').invoke('val', '');
    cy.get('#dateOfBirthInput').type('05/11/1988');
    cy.get('#dateOfBirthInput').type('{enter}');
    cy.get('.subjects-auto-complete__value-container').click();
    cy.get('#subjectsInput').invoke('val', '');
    cy.get('#subjectsInput').type('Computer');
    cy.get('#react-select-2-option-0').click();
    cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').click();
    cy.get('#hobbies-checkbox-1').check();
    cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').click();
    cy.get('#hobbies-checkbox-2').check();
    cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').click();
    cy.get('#hobbies-checkbox-3').check();
    cy.get('#uploadPicture').click();
    const fileName = 'myFile.txt';
    cy.get('#uploadPicture').attachFile(fileName);
    cy.get('#currentAddress').click();
    cy.get('#currentAddress').type('Street 5th, 655');
    cy.get('.css-yk16xz-control > .css-1hwfws3 > .css-1wa3eu0-placeholder').click();
    cy.get('#react-select-3-option-0').click();
    cy.get('#city > .css-yk16xz-control > .css-1hwfws3').click();
    cy.get('#react-select-4-option-0').click();
    cy.get('#submit').click();
    cy.get('#example-modal-sizes-title-lg').click();
    cy.get('#example-modal-sizes-title-lg').should('have.text', 'Thanks for submitting the form');
    cy.get('.modal-body').scrollTo('bottomRight', {ensureScrollable:false});
    cy.get('#closeLargeModal').click();
  });
});
